# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_stream.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'image_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_stream.proto\x12\x0bimagestream\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\" \n\rImageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\x0bImageStream\x12\x42\n\tSendImage\x12\x19.imagestream.ImageRequest\x1a\x1a.imagestream.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=35
  _globals['_IMAGEREQUEST']._serialized_end=69
  _globals['_IMAGERESPONSE']._serialized_start=71
  _globals['_IMAGERESPONSE']._serialized_end=103
  _globals['_IMAGESTREAM']._serialized_start=105
  _globals['_IMAGESTREAM']._serialized_end=186
# @@protoc_insertion_point(module_scope)
